[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "dbus",
  "expat",
  "libxcb",
  "libxkbcommon",
  "gtk3",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "glib"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[start]
cmd = "gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:$PORT"
